### ISSUE TITLE
Tutorial Page fiori-ios-hcpms-setup.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/sap-mobile-development-kit#2]
Tutorial issue found: [https://github.com/sap-tutorials/sap-mobile-development-kit/blob/master/tutorials/fiori-ios-hcpms-setup/fiori-ios-hcpms-setup.md](https://github.com/sap-tutorials/sap-mobile-development-kit/blob/master/tutorials/fiori-ios-hcpms-setup/fiori-ios-hcpms-setup.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- software-product>ios-sdk-for-sap-btp
- software-product>android-sdk-for-sap-btp

 Affected server: PROD

**Comment by jitendrakansal** [comment]
fixed it. Thanks 
@jmmargo can i close this issue myself?

**Comment by jmmargo** [comment]
Jitendra, if you have access to close the issue, please do so.  As the repo admin, you should have access.  Thanks.
