### ISSUE TITLE
Set Up Initial Configuration for an MDK App

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/sap-mobile-development-kit#21]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-ms-setup.html
--------------------------

The tutorial layout seems to be broken

**Comment by jitendrakansal** [comment]
@peterpersiel do you still see layout broken? If not, please close.

**Comment by jitendrakansal** [comment]
@peterpersiel do you still see layout broken? If not, please close.

**Comment by jitendrakansal** [comment]
No response from user. Assuming issue is no longer exist. Closing this.
