### ISSUE TITLE
Enhance Your First MDK App with Additional Functionalities

### ISSUE THREAD

**Issue by peterpersiel** [sap-tutorials/sap-mobile-development-kit#23]
Tutorials: https://developers.sap.com/mission.mobile-dev-kit-enhance.html
--------------------------

Layout is broken

**Comment by jitendrakansal** [comment]
@peterpersiel do you still see layout broken? If not, please close.

**Comment by jitendrakansal** [comment]
No response from user. Assuming issue is no longer exist. Closing this.
