### ISSUE TITLE
Aggregations for extension controls

### ISSUE THREAD

**Issue by singhc00** [sap-tutorials/sap-mobile-development-kit#247]
I have been going through the documentation for custom controls using Native Script. Is it not possible to add aggregations to custom controls? Similar to Button Table and Button in the MDK, I want to build a custom control where I need multiple items as part of the main control.

**Comment by jitendrakansal** [comment]
@singhc00 do you have a mockup to share on what you wanting to have multiple items on a page?

**Comment by singhc00** [comment]
@jitendrakansal : thank you for your reply. I will mark this as closed as I am able to achieve that functionality using extension properties array. I was hoping that I could create a custom control where I can drag and drop other custom controls. But extension properties gives a lot of flexibility.
