### ISSUE TITLE
Create a Slider Custom Control in an MDK App (Using Metadata Approach)

### ISSUE THREAD

**Issue by NitinKaneri** [sap-tutorials/sap-mobile-development-kit#248]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-slider-extension.html
--------------------------
I am following the above tutorial for create the MDK Slider for the customer controler, however under Step1: Create a new MDK project in SAP Business Application Studio -> sub-step 4 screenshot is not having the Finish option, It is asking me for the Service Configuration. Attached screenshot. 
<img width="1279" alt="MDK Extension" src="https://github.com/sap-tutorials/sap-mobile-development-kit/assets/49900219/a52f87dd-e220-43aa-8997-6d057b10d3d1">

Here is the screenshot of My trail setup. Am I missing anything.
<img width="1279" alt="MyProject MDK Extesion" src="https://github.com/sap-tutorials/sap-mobile-development-kit/assets/49900219/acf94625-be1d-482f-bb24-78d4ce993b73">

**Comment by jitendrakansal** [comment]
@NitinKaneri Please select **Empty** for **MDK Template Type** field.

We'll fix the mandatory validation for this in the UI.

**Comment by NitinKaneri** [comment]
It worked. Thank you @jitendrakansal
