### ISSUE TITLE
Start Your MDK Application in the Editor

### ISSUE THREAD

**Issue by jastill** [sap-tutorials/sap-mobile-development-kit#61]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html
--------------------------

Write here how you think we can improve the tutorial ...

The QR code for iOS points to the SAP Mobile Cards app in the App Store, not the SAP Mobile Services Client.

**Comment by jitendrakansal** [comment]
@jastill Thanks for reporting, fixed it. Please check.

**Comment by jitendrakansal** [comment]
No response from user. Assuming issue is no longer exist. Closing this.
