### ISSUE TITLE
Start Your MDK Application in the Editor

### ISSUE THREAD

**Issue by KevinBraunSCL** [sap-tutorials/sap-mobile-development-kit#64]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html
--------------------------
In this tutorial, the QR Code for iOS takes you to the wrong app.  It is currently taking you do the SAP Mobile Cards app, not the Mobile Srvs app.

**Comment by jitendrakansal** [comment]
@KevinBraunSCLThanks for reporting, fixed it. Please check.

**Comment by jitendrakansal** [comment]
No response from user. Assuming issue is no longer exist. Closing this.
