### ISSUE TITLE
Access SAP Mobile Services

### ISSUE THREAD

**Issue by kelghali** [sap-tutorials/sap-mobile-development-kit#65]
Tutorials: https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html
--------------------------

By using the trial account, it is crucial to select 'Singapore' (Azure) as your region/Provider.
Failure to choose 'Singapore' may result in authentication issues when attempting to log in to the Mobile Services Dashboard Trial (Step 2.5).

Any other region (e.g. 'US', AWS) could lead to difficulties in accessing the trial services.
Always ensure 'Singapore' (Azure) is specified to guarantee a seamless authentification.

**Comment by jitendrakansal** [comment]
@kelghali What issue did you encounter when choosing US region? I have a running trial in US10, not seeing any authentication related challenges.

**Comment by jitendrakansal** [comment]
No response from user. Assuming issue is no longer exist. Closing this.
